blank_issues_enabled: false
contact_links:
  - name: AWS IoT EduKit Community Support
    url: https://github.com/aws-samples/aws-iot-edukit-tutorials/discussions
    about: Please ask and answer questions here.
